default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: doidi
  password: doidi
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: doidi_development

test:
  <<: *default
  database: doidi_test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['DBNAME'] %>
  pool: 7
  username: <%= ENV['DBUSERNAME'] %>
  password: <%= ENV['DBPASS'] %>
