# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e4c11e38181598c62980db2f2db728fe9fc5ec8b9feb555770cd6d0a96f2257700f13a4b4ca2945e77233741156b95bffe0f98bf5c5d713f29ec6f70cd76dd4

test:
  secret_key_base: be021589ca78a29707f636f2eb2138599ba6e7bb28002f94a376635d30ed2679ac22d8179632d4a18388a7fe68f38651b7f3e0f10e1c692236cb224fdebe7470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
